<?php
declare(strict_types=1);

namespace Tests\Feature;

use Tests\TestCase;

/**
 * 文章鉴权功能测试:非作者 403、作者可改、404、401、公开列表仅已发布。
 */
final class PostAuthorizationTest extends TestCase
{
    public function testNonAuthorCannotUpdatePost(): void
    {
        $this->registerUser('Alice', 'alice@example.com');
        $aliceToken = $this->login('alice@example.com');

        $create = $this->request('POST', '/api/v1/posts', [
            'title' => 'Alice 的文章',
            'content' => '内容',
            'status' => 'published',
        ], token: $aliceToken);
        self::assertSame(201, $create->getStatusCode());
        $postId = $this->decode($create)['data']['id'];

        $this->registerUser('Bob', 'bob@example.com');
        $bobToken = $this->login('bob@example.com');

        $response = $this->request('PUT', '/api/v1/posts/' . $postId, [
            'title' => '被篡改的标题',
        ], token: $bobToken);

        self::assertSame(403, $response->getStatusCode());
        $payload = $this->decode($response);
        self::assertFalse($payload['success']);
        self::assertSame('forbidden', $payload['error']['code']);
    }

    public function testNonAuthorCannotDeletePost(): void
    {
        $this->registerUser('Alice', 'alice@example.com');
        $aliceToken = $this->login('alice@example.com');
        $postId = $this->decode($this->request('POST', '/api/v1/posts', [
            'title' => 'Alice 的文章',
            'content' => '内容',
        ], token: $aliceToken))['data']['id'];

        $this->registerUser('Bob', 'bob@example.com');
        $bobToken = $this->login('bob@example.com');

        $response = $this->request('DELETE', '/api/v1/posts/' . $postId, token: $bobToken);

        self::assertSame(403, $response->getStatusCode());
    }

    public function testAuthorCanUpdateOwnPost(): void
    {
        $this->registerUser('Alice', 'alice@example.com');
        $token = $this->login('alice@example.com');
        $postId = $this->decode($this->request('POST', '/api/v1/posts', [
            'title' => '原标题',
            'content' => '内容',
        ], token: $token))['data']['id'];

        $response = $this->request('PUT', '/api/v1/posts/' . $postId, [
            'title' => '新标题',
            'status' => 'published',
        ], token: $token);

        self::assertSame(200, $response->getStatusCode());
        $data = $this->decode($response)['data'];
        self::assertSame('新标题', $data['title']);
        self::assertSame('published', $data['status']);
    }

    public function testUpdateMissingPostReturns404(): void
    {
        $this->registerUser('Alice', 'alice@example.com');
        $token = $this->login('alice@example.com');

        $response = $this->request('PUT', '/api/v1/posts/999999', ['title' => 'x'], token: $token);

        self::assertSame(404, $response->getStatusCode());
    }

    public function testCreatePostRequiresAuthentication(): void
    {
        $response = $this->request('POST', '/api/v1/posts', ['title' => 't', 'content' => 'c']);

        self::assertSame(401, $response->getStatusCode());
    }

    public function testPublicListOnlyShowsPublishedPosts(): void
    {
        $this->registerUser('Alice', 'alice@example.com');
        $token = $this->login('alice@example.com');
        $this->request('POST', '/api/v1/posts', ['title' => '草稿', 'content' => 'c'], token: $token);
        $this->request('POST', '/api/v1/posts', ['title' => '已发布', 'content' => 'c', 'status' => 'published'], token: $token);

        $response = $this->request('GET', '/api/v1/posts');
        $payload = $this->decode($response);

        self::assertSame(1, $payload['meta']['total']);
        self::assertSame('已发布', $payload['data'][0]['title']);
    }

    public function testSlugAutoGeneratedAndUnique(): void
    {
        $this->registerUser('Alice', 'alice@example.com');
        $token = $this->login('alice@example.com');

        $first = $this->decode($this->request('POST', '/api/v1/posts', ['title' => 'Same Title', 'content' => 'c'], token: $token))['data'];
        $second = $this->decode($this->request('POST', '/api/v1/posts', ['title' => 'Same Title', 'content' => 'c'], token: $token))['data'];

        self::assertNotSame($first['slug'], $second['slug']);
    }
}
